{
  imports = [
    ./mini.nix
    ./flash.nix
    ./comment.nix
    ./colorizer.nix
    ./undotree.nix
    ./harpoon.nix
    ./illuminate.nix
    ./autopairs.nix
    ./oil.nix
    ./yanky.nix
    ./markview.nix
    ./nabla.nix
    ./mkdnflow.nix
    ./web-devicons.nix
    ./spectre.nix
    ./grug-far.nix
    ./texpresso.nix
    ./vim-bbye.nix
    ./todo-comments.nix
    ./claude-code.nix
  ];
}
