# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4b8e2989-ed63-45d3-923c-d19dda1e3615";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  boot.initrd.luks.devices."crypted".device = "/dev/disk/by-uuid/212e688d-d8e5-4c20-849d-3e9b9282a90b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6ACD-77D3";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/4b8e2989-ed63-45d3-923c-d19dda1e3615";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/4b8e2989-ed63-45d3-923c-d19dda1e3615";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/4b8e2989-ed63-45d3-923c-d19dda1e3615";
      fsType = "btrfs";
      options = [ "subvol=persist" ];
    };

  fileSystems."/snapshots" =
    { device = "/dev/disk/by-uuid/4b8e2989-ed63-45d3-923c-d19dda1e3615";
      fsType = "btrfs";
      options = [ "subvol=snapshots" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/4b8e2989-ed63-45d3-923c-d19dda1e3615";
      fsType = "btrfs";
      options = [ "subvol=tmp" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/4b8e2989-ed63-45d3-923c-d19dda1e3615";
      fsType = "btrfs";
      options = [ "subvol=log" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/7802dd38-97b1-41ba-81cb-bf5e98657f50"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
