{
  imports = [
    ./mini.nix
    ./flash.nix
    ./comment.nix
    ./neotree.nix
    ./colorizer.nix
    ./comment-box.nix
    ./transparent.nix
    ./undotree.nix
    ./harpoon.nix
    ./snipe.nix
    ./illuminate.nix
    ./ufo.nix
    ./autopairs.nix
    ./oil.nix
    ./floaterm.nix
    ./multicursors.nix
    ./neoclip.nix
    ./markview.nix
    ./obsidian.nix
    ./muren.nix
  ];
}
