# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.loader.grub.device = "/dev/sda";

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/38201a8e-1d66-4b14-b291-3012100e4962";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  boot.initrd.luks.devices."crypted".device = "/dev/disk/by-uuid/1e0aac2f-f9db-4fe4-8332-5df6b44749b2";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6CED-6371";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/38201a8e-1d66-4b14-b291-3012100e4962";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/38201a8e-1d66-4b14-b291-3012100e4962";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/38201a8e-1d66-4b14-b291-3012100e4962";
      fsType = "btrfs";
      options = [ "subvol=persist" ];
    };

  fileSystems."/snapshots" =
    { device = "/dev/disk/by-uuid/38201a8e-1d66-4b14-b291-3012100e4962";
      fsType = "btrfs";
      options = [ "subvol=snapshots" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/38201a8e-1d66-4b14-b291-3012100e4962";
      fsType = "btrfs";
      options = [ "subvol=tmp" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/38201a8e-1d66-4b14-b291-3012100e4962";
      fsType = "btrfs";
      options = [ "subvol=log" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b80de09f-c53e-453e-8f56-8db6cae16a8b"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens18.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
