# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/4831dd16-5c51-483c-9b23-dab737d8ca3d";
    fsType = "btrfs";
    options = ["subvol=root"];
  };

  boot.initrd.luks.devices."crypted".device = "/dev/disk/by-uuid/c467b5a6-9e82-46d1-af96-c2a53b1dfcd8";

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/4831dd16-5c51-483c-9b23-dab737d8ca3d";
    fsType = "btrfs";
    options = ["subvol=nix"];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/4831dd16-5c51-483c-9b23-dab737d8ca3d";
    fsType = "btrfs";
    options = ["subvol=log"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/4831dd16-5c51-483c-9b23-dab737d8ca3d";
    fsType = "btrfs";
    options = ["subvol=home"];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/4831dd16-5c51-483c-9b23-dab737d8ca3d";
    fsType = "btrfs";
    options = ["subvol=persist"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/66F3-33AC";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/snapshots" = {
    device = "/dev/disk/by-uuid/4831dd16-5c51-483c-9b23-dab737d8ca3d";
    fsType = "btrfs";
    options = ["subvol=snapshots"];
  };

  fileSystems."/tmp" = {
    device = "/dev/disk/by-uuid/4831dd16-5c51-483c-9b23-dab737d8ca3d";
    fsType = "btrfs";
    options = ["subvol=tmp"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/0aabe911-cd76-4403-a3ac-9429f6b2eb94";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp24s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
