# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/c4f37852-a80b-4d85-b24c-22abf1fbcc00";
    fsType = "btrfs";
    options = ["subvol=root"];
  };

  boot.initrd.luks.devices."crypted".device = "/dev/disk/by-uuid/b0a1f752-4ba1-4791-8e7c-99a2dbe4137d";

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/c4f37852-a80b-4d85-b24c-22abf1fbcc00";
    fsType = "btrfs";
    options = ["subvol=nix"];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/c4f37852-a80b-4d85-b24c-22abf1fbcc00";
    fsType = "btrfs";
    options = ["subvol=log"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/c4f37852-a80b-4d85-b24c-22abf1fbcc00";
    fsType = "btrfs";
    options = ["subvol=home"];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/c4f37852-a80b-4d85-b24c-22abf1fbcc00";
    fsType = "btrfs";
    options = ["subvol=persist"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/B02C-A702";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/tmp" = {
    device = "/dev/disk/by-uuid/c4f37852-a80b-4d85-b24c-22abf1fbcc00";
    fsType = "btrfs";
    options = ["subvol=tmp"];
  };

  fileSystems."/snapshots" = {
    device = "/dev/disk/by-uuid/c4f37852-a80b-4d85-b24c-22abf1fbcc00";
    fsType = "btrfs";
    options = ["subvol=snapshots"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/2a9f7be7-6cf7-4111-b72d-81c3dc68a91b";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp24s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
