{
  config,
  lib,
  ...
}: {
  programs.ssh = lib.mkIf (config.systemSettings.profile == "work") {
    enable = true;
    enableDefaultConfig = false;

    # Work hostnames are in SOPS-decrypted config at /etc/ssh/ssh_config.d/work-hosts.conf
    # Generated by sops.templates."ssh-work-config" in machines/fafn1r/nix/sops.nix
    includes = [
      "/etc/ssh/ssh_config.d/work-hosts.conf"
    ];

    matchBlocks = {
      "*" = {
        extraOptions = {
          AddKeysToAgent = "yes";
        };
      };
    };
  };
}
