{
  imports = [
    ./telescope.nix
    ./which-key.nix
    ./alpha.nix
    ./precognition.nix
    ./barbar.nix
    ./noice.nix
    ./nvim-notify.nix
    ./yazi.nix
    ./yaml_companion.nix
    ./image.nix
    ./auto-session.nix
    ./lualine.nix
    ./staline.nix
    ./navic.nix
    ./navbuddy.nix
    ./marks.nix
    ./web-devicons.nix
    ./vimade.nix
    #./helpview.nix
  ];
}
