{
  imports = [
    ./telescope.nix
    ./neotree.nix
    ./which-key.nix
    ./alpha.nix
    ./precognition.nix
    ./noice.nix
    ./nvim-notify.nix
    ./image.nix
    ./auto-session.nix
    ./lualine.nix
    ./marks.nix
    ./vimade.nix
    ./twilight.nix
    ./transparent.nix
    ./toggleterm.nix
  ];
}
