# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["xhci_pci" "nvme" "usb_storage" "sd_mod"];
      kernelModules = [];
      luks.devices."crypted".device = "/dev/disk/by-uuid/13ed3fdb-5215-4cfb-94b3-af8f22ceb2b3";
    };
    kernelModules = ["kvm-intel"];
    extraModulePackages = [];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/acb7478d-1bfd-4c1e-87f9-9e21632f772a";
    fsType = "btrfs";
    options = ["subvol=root"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/01BA-8F7F";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/acb7478d-1bfd-4c1e-87f9-9e21632f772a";
    fsType = "btrfs";
    options = ["subvol=home"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/acb7478d-1bfd-4c1e-87f9-9e21632f772a";
    fsType = "btrfs";
    options = ["subvol=nix"];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/acb7478d-1bfd-4c1e-87f9-9e21632f772a";
    fsType = "btrfs";
    options = ["subvol=persist"];
  };

  fileSystems."/snapshots" = {
    device = "/dev/disk/by-uuid/acb7478d-1bfd-4c1e-87f9-9e21632f772a";
    fsType = "btrfs";
    options = ["subvol=snapshots"];
  };

  fileSystems."/tmp" = {
    device = "/dev/disk/by-uuid/acb7478d-1bfd-4c1e-87f9-9e21632f772a";
    fsType = "btrfs";
    options = ["subvol=tmp"];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/acb7478d-1bfd-4c1e-87f9-9e21632f772a";
    fsType = "btrfs";
    options = ["subvol=log"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/8a73a604-7c4c-4065-b1e7-91fc8616b02c";}
  ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
